### ISSUE TITLE
How to build our custom http header and send it?

### ISSUE THREAD

**Issue by shaozhihua** [oktal/pistache#1005]
I know,in the "examples" folder.The project has a "custom_header.cc" file,I already know how to create a custom header class which inherite Http::Header::Header.
but I do not know how to send it to the client;in other word,I can't control my own http message ,
response line, response header, I only can control the body,because has example,I am not smart,so I only can find some examples,
But I didn't find the response Line , header send example..
I hope someone can help me if you are free.
thank you so much!

**Comment by shaozhihua** [comment]
yeah,actually I know how to solve several hours ago:
here:
void Server::onRequest(const Http::Request &request, Http::ResponseWriter response)
{
    response.headers().add<Http::Header::AccessControlAllowOrigin>("*"); 
    response.headers().add<TheClassNameWhichICustom>();
    //ofcourse before write these two lines code,we should register first. 
    //Http::Header::Registry::instance().registerHeader<TheClassNameWhichICustom>();
    response.send(Http::Code::Ok,messagebody);

}
I think the example file custom_header.cc doesn't reflect this usage,I suggest you smart guys should update this example.I don't know.

**Comment by Junfou** [comment]
> yeah,actually I know how to solve several hours ago: here: void Server::onRequest(const Http::Request &request, Http::ResponseWriter response) { response.headers().add[Http::Header::AccessControlAllowOrigin](Http::Header::AccessControlAllowOrigin)("*"); response.headers().add(); //ofcourse before write these two lines code,we should register first. //Http::Header::Registry::instance().registerHeader(); response.send(Http::Code::Ok,messagebody);

Can you provide a relatively complete code implementation？thanks！
