### ISSUE TITLE
X-Auth-Token HTTP header

### ISSUE THREAD

**Issue by ivanocerrato** [oktal/pistache#110]
Hi, in the project in which I am involved in, we need to use the HTTP header "X-Auth-Token".
I have then created the [XAuthToken](https://github.com/netgroup-polito/un-orchestrator/blob/master/orchestrator/node_resource_manager/rest_server/x-auth-token-header.h) class that extends the Pistache Header::Header class.

I have registered the class with this line of code

``` c
	Header::Registry::registerHeader<XAuthToken>();
```

and added the following code to retrieve the header 

```c
	auto token_header = headers.get<XAuthToken>();
	string t = token_header->token();
```

However, although the HTTP request I have received actually has the header, Pistache always says that it is not found into the packet.

Then I have changed the name of the header in **XAuth-Token** and **XAuthToken**, by simply changing the string at [this line](https://github.com/netgroup-polito/un-orchestrator/blob/master/orchestrator/node_resource_manager/rest_server/x-auth-token-header.h#L16), and the header was recognized properly into the packet.
Then, I have also tried to call that header **X-AuthToken**, and it was not recognized.
Then, it seems that Pistache is not able to identify the `-` between the `X` and the `A`.

Am I doing something wrong, or is there a bug into the code?

**Comment by oktal** [comment]
Hello.

This is weird, the header should be correctly parsed and found, with and without dashes.

Is it sill happening ?

**Comment by ivanocerrato** [comment]
We changed REST client at it works.
