### ISSUE TITLE
how to use docs/Doxyfile.in to generate document?

### ISSUE THREAD

**Issue by edidada** [oktal/pistache#1108]
doxygen Doxyfile.in
warning: tag INPUT: input source '@SOURCE_DIR@/README.md' does not exist
warning: tag INPUT: input source '@SOURCE_DIR@/src/' does not exist
warning: tag INPUT: input source '@SOURCE_DIR@/include/' does not exist
warning: tag INPUT: input source '@SOURCE_DIR@/examples/' does not exist
warning: tag INPUT: input source '@SOURCE_DIR@/docs/' does not exist
error: tag OUTPUT_DIRECTORY: Output directory '@CURRENT_BUILD_DIR@/docs/' does not exist and cannot be created
Exiting...

**Comment by edidada** [comment]
run this in bash

cd pistache
meson setup build \
    --buildtype=release \
    -DPISTACHE_USE_SSL=true \
    -DPISTACHE_BUILD_EXAMPLES=true \
    -DPISTACHE_BUILD_TESTS=true \
    -DPISTACHE_BUILD_DOCS=true \
    --prefix="$PWD/prefix"
meson install -C build
doxygen build/docs/Doxyfile

**Comment by Tachi107** [comment]
Alternatively, you can pass `-DPISTACHE_BUILD_DOCS=true` when running `meson setup`, and then run `meson compile -C build docs`
