### ISSUE TITLE
Issue at application compile time

### ISSUE THREAD

**Issue by wyatthuckaby** [oktal/pistache#133]
After following the build instructions on the website, I built my first server, and when I went to compile. It fell on its face saying the namespace "Net " is not defined. I'm pretty sure I'm missing something stupid but I might need a second pair of eyes. I'm attempting build with the following:

`g++ -lpistache main.cpp`

**Comment by djbb7** [comment]
I am running into the same issue. Have you tried with `-lnet` instead?

**Comment by jgh-** [comment]
Somewhere in one of the recent releases the namespace changed.  It looks like the readme is out of date now.  You want to use the `Pistache` namespace instead of the `Net` namespace now.

**Comment by wyatthuckaby** [comment]
I think we're really close... Using Pistache instead of net worked like a charm but the assemble step failed stating it was unable to find the pthread_create library. directly linking to -pthread seemed to fix it. Thank you all for your help :)

**Comment by jgh-** [comment]
yeah you always need to link to pthreads when using C++ threading.

**Comment by wyatthuckaby** [comment]
Oops forgot to close the issue, my apologies :)
