### ISSUE TITLE
RUSAGE_THREAD not declared

### ISSUE THREAD

**Issue by MonkeySlut** [oktal/pistache#158]
Hi :)
During 'make' of pistache in docker image I get:
> 'RUSAGE_THREAD' was not declared in this scope
> auto res = getrusage(RUSAGE_THREAD, &now);

I would have used pistache-docker image but it's out of date and has a critical bug for me.
I tried using:

> #define __USE_GNU
> #include <sys/resource.h>

without any luck, anyone can bring some insights?

**Comment by xoac** [comment]
You need to deliver more information about docker image. It's looks like a version of your libs don't have defined `RUSAGE_THREAD`.

**Comment by MonkeySlut** [comment]
Apparently, this was a problem with the docker image, seems strange because it's an ubuntu image...
I instead used alpine docker image, works fine.
Closing issue :)
