### ISSUE TITLE
Issue compiling project using pistache

### ISSUE THREAD

**Issue by narva8916** [oktal/pistache#168]
I added pistache external reference and trying to compile the project the next error is shown:

/ext-libs/pistache/libpistache.a(listener.cc.o):-1: In function `Pistache::Tcp::Listener::runThreaded()':

What can i do in order to solve this issue?

**Comment by xoac** [comment]
You probably past just a part of error. Please past more.

**Comment by narva8916** [comment]
Hi, thanks for the quick response, 

I'm using QtCreator and this is the full error message:

g++ -m64 -o alpr main.o   -L/home/ubuntu/alpr/ext-libs/pistache/ -lpistache
/home/ubuntu/alpr/ext-libs/pistache//libpistache.a(listener.cc.o): In function `Pistache::Tcp::Listener::runThreaded()':
listener.cc:(.text+0x1a48): undefined reference to `pthread_create'
/home/ubuntu/alpr/ext-libs/pistache//libpistache.a(reactor.cc.o): In function `Pistache::Aio::AsyncImpl::run()':
reactor.cc:(.text._ZN8Pistache3Aio9AsyncImpl3runEv[_ZN8Pistache3Aio9AsyncImpl3runEv]+0xc8): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status

Thanks in advance.

**Comment by xoac** [comment]
haven't u forgot to link against `-lpthread`?

**Comment by narva8916** [comment]
How can i link against -lpthread? 

I'm barely learning c++.

**Comment by narva8916** [comment]
Thanks xoac!!! it's working now!
