### ISSUE TITLE
Restart server (shutdown doens't unbind address)

### ISSUE THREAD

**Issue by paoloach** [oktal/pistache#178]
I would add a new route when the server is running.
I see in the code that you clone the route, so I thought that this feature is intentionally missing.

So I try to restart the server add a new route in this way:
Pistache::Http::Endpoint server;
// init server
server.serveThreaded()
// some code
server.shutdown()
server.serveThreaded()

but I got the error
 epoll_ctl(epoll_fd, EPOLL_CTL_ADD, fd, &ev): Bad file descriptor
then Pistache try to bind as the shutdown method doesn't unbind.
Really, calling my rest method after the shutdown, the connection remains appended (as the server is blocked) instead of refusing it.

**Comment by xoac** [comment]
duplicated  by #164

**Comment by oktal** [comment]
Hello, closing this issue in favor of #164
