### ISSUE TITLE
"Bad file descriptor error"

### ISSUE THREAD

**Issue by booniedock** [oktal/pistache#18]
I'm trying to run the example files (and they run sometimes), but I get this error intermittently. Any ideas? Many thanks.

```
$ examples/http_server 9500 2
Cores = 4
Using 2 threads
terminate called after throwing an instance of 'std::runtime_error'
  what():  epoll_ctl(epoll_fd, EPOLL_CTL_ADD, fd, &ev): Bad file descriptor
[1]    12311 abort (core dumped)  examples/http_server 8000 2
```

**Comment by oktal** [comment]
Hello,

This error will show up when the listen fd has not be closed correctly either because it did not shutdown gracefully and the socket fd is in TIME_WAIT mode or because the program is still running and thus the fd is still bound (LISTEN mode).

How are you shutdowning the progam ?

**Comment by booniedock** [comment]
I was doing Ctrl+C and the example program did receive the signal and display the shutdown message. Not sure why the socket was not being closed still.

Anyway, I was able to resolve the issue by passing the SO_REUSEADDR flag. Thank you.

**Comment by arj** [comment]
I recommend reopening that. Shutting down the application with Ctrl+C or a normal kill <PID> should close the socket gracefully.
