### ISSUE TITLE
What is the meaning of the question mark in the POST handler of the rest_server example?

### ISSUE THREAD

**Issue by gitoops** [oktal/pistache#196]
Hi,
probably a stupid question but please can you tell me what the meaning of the question mark in
`Routes::Post(router, "/record/:name/:value?", Routes::bind(&StatsEndpoint::doRecordMetric, this));`
in `rest_server.cc` (line 61)
When I try with 
`curl -i -X POST  http://127.0.0.1:9080/record/jan/1`
it works with and without question mark.

Thanks
Jan

**Comment by oktal** [comment]
Hello, a question mark means that the parameter is optional.

For a given `/record/:name/:value?` route, both

`/record/requests/10` and `/record/requests/` will be matched. The first one will also match the `:value` parameter with `10`.
