### ISSUE TITLE
Question: How would I deploy this application to production?

### ISSUE THREAD

**Issue by FreddieOD** [oktal/pistache#203]
I've read to user manual and I suspect I might be suffering a bit of confusion. Can someone tell me how this is to be deployed to a production server fronted by something like Nginx or Apache? I am noticing this is itself a server, so this leads me to think that we should be proxy passing client requests going to my Nginx server on to my pistache server listening on an internal port?? Is this a good strategy over something like, say, fastcgi? 

Thanks for your time.

**Comment by jeffvandyke** [comment]
I think that strategy should work just fine. Another arguable approach would be to have Pistache be the only server, but Nginx has more options and flexibility than Pistache does (e.g., https, caching), so Nginx as a reverse-proxy to Pistache would be best if you can pull it off.

**Comment by FreddieOD** [comment]
Hello and thank you for the reply. Fronting this Pistache server and listening on port 80 (reserved port for HTTP calls) is a bit of an admin nightmare in my opinion, since port 80 is a reserved port and whatever is listening on port 80 should be production grade; reliable, reject unauthorised calls, seamless addition of functionality, etc, etc. Pistache, while an impressive library, is not what I would consider a production ready HTTP server.

Implementing a reverse proxy is much simpler than implementing fastCGI and so I think I will stick with this library for now. I will add my 2c here once I have it up and running and let you and others make up their minds.
