### ISSUE TITLE
cannot find -lnet

### ISSUE THREAD

**Issue by gitspider** [oktal/pistache#214]
ubuntu 16, g++ version 5
my command: 
```
g++ server.cpp -lnet -std=c++11 -o server
/usr/bin/ld: cannot find -lnet
collect2: error: ld returned 1 exit status

```
How could I solve this problem? Please help me. Thanks

**Comment by jeffvandyke** [comment]
Did you check out #135? `-lnet` changed to `-lpistache`

**Comment by gitspider** [comment]
Ok, solved.
