### ISSUE TITLE
accepting POST data larger than 1024

### ISSUE THREAD

**Issue by dicknose** [oktal/pistache#22]
I seem to be having a problem when the server is getting POST data that is long.
Using the example http_server and sending:
curl 0.0.0.0:9080/echo -H "Content-Type: application/xml" -d @sample.xml

the server will echo back if the size of sample.xml is less than 1024. Bigger and it just hangs, no response. I changed the test http_server to cout the length of body() before doing the echo response and it doesnt output anything on these large sets, implying to me that the handler is not even called.

**Comment by oktal** [comment]
Hello,

Could you please provide the request that is issued by curl ? Simply add `-vv` to your request and it should output the whole request that it's sending to the server.

**Comment by dicknose** [comment]
Got it… and now I can see its a “expect 100-Continue” issue, obviously triggered by the data size going past 1024.

$ curl 0.0.0.0:9080/echo -vv -H "Content-Type: application/xml" -d @long.xml
* About to connect() to 0.0.0.0 port 9080 (#0)
*   Trying 0.0.0.0... connected
* Connected to 0.0.0.0 (0.0.0.0) port 9080 (#0)
> POST /echo HTTP/1.1
> User-Agent: curl/7.19.7 (i386-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 0.0.0.0:9080
> Accept: */*
> Content-Type: application/xml
> Content-Length: 2419
> Expect: 100-continue
>
* Done waiting for 100-continue
^C

I can’t see an option for curl to NOT enable the expect 100. 
I wont be writing the client apps that will use my server so Im not sure if they will have the same behaviour.

David

**Comment by dicknose** [comment]
And after a quick google I found how to turn this behaviour off in curl!
Force an expect header, so I add
-H “Expect: "

So I guess this turns into
“Does not support 'Expect: 100-continue’ “

but Im happy I can continue with my work!
And thanks for your efforts in writing this and supporting it. It seems a great framework, nice and simple to use.

David

**Comment by dicknose** [comment]
Now I see there is a 4k limit, but thats coded in!

**Comment by sebt3** [comment]
the same 4k limit exist also in the client side of pistache. That's an issue when reading an XML file (which easyly exceed these 4k in size).
I would love to see theses limits removed

**Comment by oktal** [comment]
You're right, Pistache currently has a 4k internal buffer limit. I'd also like to lift that limit and make it configurable at run-time. We could also have a "small buffer" optimization where we would like the 4k stack-allocated buffer and then allocate a buffer on the heap only if it is needed so that most requests won't require a heap allocation

**Comment by cneira** [comment]
I have the same issue a runtime config is nice to have I'll give it a shot.

**Comment by cneira** [comment]
I just added a fix for this, I have not measured performance yet, I replace the char array with a stl vector to be able to resize it at runtime. 

https://github.com/cneira/pistache

**Comment by oktal** [comment]
Hello,

Great ! Would you be able to submit a Pull Request ?

**Comment by cneira** [comment]
Hi I'm still testing this change after I complete testing I'll do a pull request
