### ISSUE TITLE
Featurerequest: Add a 'precondition' to Router.

### ISSUE THREAD

**Issue by bamkrs** [oktal/pistache#24]
While using Pistache, I often use the same common code in every Handler for every route.
Something like (Attention: Mostly pseudocode, but you get the idea)

```
response.headers().add(/*Contenttype*/);
ownObject* oo = new ownObject();
if(oo->isAlive())
{
  // Actual Work for Handler
  // Send and Return if successfull
}
oo->foo = 1;
oo->bar = "Service Unavailable";
response.send(Http::Code::Service_Unavailable,oo->dump());
delete oo;
```

Wouldn't it be nice to add a function to the Router that gets called before the actual handler kicks in?

```
Router->addPreworker(/*ptrToFunction*/)
```

Preworkerfunction:

```
void preFunc(Router, request, response){     //or only request, response
  //do stuff
  if(!router->for(request)->callHandler()) {   //and do something like request->callHandler()
    //handler would be bool instead of void and return true when everything went fine
    //and false if a common error occurs

    //do errorreport-generation
    response.send(Http::Code::Service_Unavailable,errorreport);
  }
}
```

Wouldn't be this a nice pattern to reduce code and points of failure?
Maybe I implement this by myself when I find some time.

**Comment by knadh** [comment]
+1

**Comment by oktal** [comment]
Hello,

Yes, that indeed sounds like a great suggestion. Basically, we need *filters*.

We could have two kind of filters: *before-filters* and *after-filters*. `before-filters` will be executed before each requests and can read/write the request/response. after-filters will be executed after each requests and can also read and modify the response.

Now we need to come up with a good API for this, feel free to suggest something if you have any idea :)

**Comment by knadh** [comment]
@oktal How Go does its HTTP middlewares may be a good idea here. They're just simple function wrappers, without the explicit need for having pre/post filter APIs.

**Comment by oktal** [comment]
@knadh could you provide an example on how Go is handling it ?

If you have a clear idea on how to design it as well as the API to provide, feel free to post it here so that we can discuss it

**Comment by knadh** [comment]
In Go, functions that satisfy `http.Handler` (which implements the function `ServeHTTP(ResponseWriter, *Request)`) can act as middleware. A middleware takes a handler and returns a handler (similar to pistache's `(const Rest::Request& request, Http::ResponseWriter response)`). Here's some pseudocode that illustrates this.

```go
func enforcePOST(next http.Handler) http.Handler {
  return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		http.Error(w, "Method not allowed", 405)
		return
	}

	// All good, continue the request.
    next.ServeHTTP(w, r)
  })
}

func validateUser(next http.Handler) http.Handler {
  return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	if r.Form.Get("user_id") != 1 {
		http.Error(w, "User is not authorized.", 403)
		return
	}

	// All good, continue the request.
    next.ServeHTTP(w, r)
  })
}

func helloHandler (w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello world! You got past the middleware filters")
})

// Bind the route.
http.Handle("/", validateUser(enforcePOST(helloHandler)))
````

Here, enforcePost() and validateUser() are middleware functions that can decide to fail or continue a request before it gets to the final handler, helloHandler(). Hope that makes sense.

**Comment by oktal** [comment]
Makes sense. We could have something similar in Pistache, some sort on `Middleware` concept. I personally would like to call it `Pipeline` but it's already a common term in the HTTP world so meh.

Anyway, I'll take some time to think about it. Let me know if you are interested in working on it. We could potentially join our effort and start development in a separate branch

**Comment by mohsenomidi** [comment]
we could add the Pipeline feature to project task and close this issue.
