### ISSUE TITLE
Expose Router::addRoute()?

### ISSUE THREAD

**Issue by knadh** [oktal/pistache#25]
@oktal What do you think of exposing Router::addRoute()? This'll make adding routes dynamically easier without the need for defining a handler class, or using the ::Get ... ::Post etc. methods. For example, if I have a map of routes+methods => handler references, it'd be possible to just loop through them and add them on the go.

**Comment by oktal** [comment]
Hello,

Could you please provide an example of your particular use-case ? I see what you mean, but I'm wondering it we really have to expose that function for it to work.

**Comment by knadh** [comment]
Let's say I have a large list of structs that represent routes+handlers (lots of pseudo code below). I feel this'll help when you're not hard coding the handlers.

```
struct route {
	string uri
	string method
	funcpointer *handler
}

routes = [route A, route B, route C, route D ...];
```

With addRoute() exposed.
```
for(each in routes) {
 Routes::addRoute(router, each->method, each->uri,
                  Routes::bind(each->handler));
}
```

Without addRoute() exposed.
```
for(each in routes) {
 if(each.method == Get) {
 	Routes::Get(router, each->uri, Routes::bind(each->handler));
 } else if(each.method == Post) {
 	Routes::Post(router, each->uri, Routes::bind(each->handler));
 } else if (each.method == Put) {
 	Routes::Put(router, each->uri, Routes::bind(each->handler));
 } else if (each.method == Delete) {
 	Routes::Delete(router, each->uri, Routes::bind(each->handler));
 }
}
```

**Comment by mohsenomidi** [comment]
It is fixed and now the routes works dynamically, without any loop on array or vector, this is stale and could be closed.
