### ISSUE TITLE
Building pistache for ARM

### ISSUE THREAD

**Issue by galvesribeiro** [oktal/pistache#30]
Hello! 

Thank you for this great library! As reading the documents looks like it is very well designed and looks a lot like the ASP.Net WebAPIs in C# world.

So, we are trying to build the library for one of our ARM devices and this is the output:

```
guto@GUTO-SURFACE3:/mnt/c/Dev/Linux/pistache/build$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: /mnt/c/Dev/Linux/toolchain/bin/arm-arm1176jzs-linux-gnueabi-gcc
-- Check for working C compiler: /mnt/c/Dev/Linux/toolchain/bin/arm-arm1176jzs-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /mnt/c/Dev/Linux/toolchain/bin/arm-arm1176jzs-linux-gnueabi-g++
-- Check for working CXX compiler: /mnt/c/Dev/Linux/toolchain/bin/arm-arm1176jzs-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
CMake Warning at examples/CMakeLists.txt:16 (find_package):
  By not providing "FindRapidJSON.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "RapidJSON", but CMake did not find one.

  Could not find a package configuration file provided by "RapidJSON" with
  any of the following names:

    RapidJSONConfig.cmake
    rapidjson-config.cmake

  Add the installation prefix of "RapidJSON" to CMAKE_PREFIX_PATH or set
  "RapidJSON_DIR" to a directory containing one of the above files.  If
  "RapidJSON" provides a separate development package or SDK, be sure it has
  been installed.


-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Found PythonInterp: /usr/bin/python (found version "2.7.6")
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/Dev/Linux/pistache/build
guto@GUTO-SURFACE3:/mnt/c/Dev/Linux/pistache/build$ ls
CMakeCache.txt  cmake_install.cmake  examples                  Makefile  tests
CMakeFiles      CTestTestfile.cmake  googletest-release-1.7.0  src
```

The complaining part is CMake trying to find RapidJSON. The docs say that Pistache has no dependency... Do we need to ignore that warning or should we build RapidJSON?

Also, I saw that you have interest in implement WebSocket in it, I would love to use and test it.

Thanks!

**Comment by sebt3** [comment]
RapidJson used to be requied but is not anymore. GTest is only used for unit-testing of the code and is not requiered either.

**Comment by galvesribeiro** [comment]
@sebt3 thanks, but looks like it still required:
```
[ 81%] Building CXX object examples/CMakeFiles/rest_description.dir/rest_description.cc.o
In file included from /mnt/c/Dev/Linux/pistache/examples/rest_description.cc:10:0:
/mnt/c/Dev/Linux/pistache/include/serializer/rapidjson.h:10:36: fatal error: rapidjson/prettywriter.h: No such file or directory
compilation terminated.
make[2]: *** [examples/CMakeFiles/rest_description.dir/rest_description.cc.o] Error 1
make[1]: *** [examples/CMakeFiles/rest_description.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by galvesribeiro** [comment]
Ok... I passed by the build error and now I'm having this message while trying to follow http://pistache.io/quickstart:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  eventfd(0, EFD_NONBLOCK | EFD_CLOEXEC): Function not implemented
Aborted
```

@sebt3 Any idea?

**Comment by galvesribeiro** [comment]
@oktal any ideas on how to workaround it? Thank you

**Comment by sebt3** [comment]
What is your kernel and libstdc++ version ?
Your error seems odd as this is implemented since a while now.
I would suggest you to try building on your raspberryPi instead of using this generic cross-compiling toolchain as it might not sync well enough with your real hardware

**Comment by galvesribeiro** [comment]
@sebt3 it is not a PI. It is a proprietary payment terminal:

```
/data/opt $ uname -a
Linux localhost 3.0.56+ #1 Wed Mar 9 17:26:02 CST 2016 armv6l GNU/Linux
```
libstdc++ is `libstdc++.so.6.0.21`

We can't build on the device, it has to be cross compiled. Like I said, the compilation is running OK. The problem is at runtime...

**Comment by sebt3** [comment]
Then i'm clueless, I hope @oktal will be more knowledgable.
EFD_NONBLOCK and EFD_CLOEXEC are both feature added in the late 2.6 kernel devel line( I think it's 2.6.27) So your 3.0 kernel should provide this. And this libstdc++ is new enough to provide these too...

**Comment by oktal** [comment]
Hello guys,

Thanks for reporting the issue. I'll take a look when I get some time this week-end

**Comment by galvesribeiro** [comment]
@oktal thanks for get back! Please let me know if/when you have an experimental fix so I can try that out. We really liked pistache here and want to embedd it on our devices. Thanks!

**Comment by galvesribeiro** [comment]
Guys, just to report back. I got it to work on the device! :) Although the device kernel and the libs support eventfd, it was disabled at the device Kernel. The manufacturer issued an update of the kernel for me with it enabled and now it works perfectly so far without any change on code, so thanks for trying to help.

One last thing... When `server.serve()` is called, it blocks the main thread... Is there another method that I can start a pistache service without blocking and without having to manually create a new thread?

THanks a lot! Keep the good work here! Pistache is far away compared with other webserver libs for C++ I almost feel myself on ASP.Net WebAPI :) and the only missing thing is WebSockets :)

**Comment by oktal** [comment]
Hello @galvesribeiro 

That's a great news. I was a little bit surprised that eventfd was not supported by your kernel. I guess that it could have been replaced by something else like a `pipefd` but it would have been a little bit painful.

To answer your question, yes `serve()` will start and block the event-loop in the main-thread. If you want it to start the event-loop in an other thread, just use `serveThreaded` and it won't block your main thread anymore.

As for websockets, that's something that has already been asked, but I haven't had time to implement it yet.

Thanks for the support, glad you enjoyed the framework :)

**Comment by galvesribeiro** [comment]
@oktal thanks for the support! Will keep moving here.

Please let us know if you find time to get websockets implemented.

Thanks!
