### ISSUE TITLE
Server threads hang up on large responses

### ISSUE THREAD

**Issue by jdoverholt** [oktal/pistache#33]
I'm not sure if I'm doing something wrong. I've tried  I get bad results when sending large responses. The exact threshold isn't consistent but seems to be consistent given the same response message. In my actual application, the problem threshold seems to be around 750-1000kb. I constructed a test case and it seems to handle 1mb just fine but 10mb produces the same result.

The behavior I see is that large files are sent -- sometimes successfully, sometimes not. This appears to leave the servicing thread in a hung state. After doing this n-1 times, where n is the number of threads passed into Net::Http::Endpoint::Init(), all further requests to the server hang with no response. I see no exception output from the server indicating any problems.

The attached code demonstrates it using Net::Http::serveFile(), but I observe the same result in large string results that I construct in code and pass into Net::Http::ResponseWriter::send().

To reproduce:
Test: [demo.zip](https://github.com/oktal/pistache/files/658455/demo.zip)

```
# cmake . 
# make
# ./demo &
# curl "http://127.0.0.1:8088/1e7" >/dev/null
# curl "http://127.0.0.1:8088/1e7" >/dev/null
# curl "http://127.0.0.1:8088/1e7" >/dev/null
```
The makefile will produce four dummy files for testing: 10k, 100k, 1m, and 10m.

**Comment by oktal** [comment]
Closing this issue, let's continue on https://github.com/oktal/pistache/issues/35
