### ISSUE TITLE
More information about Pistache Description Swagger

### ISSUE THREAD

**Issue by FranciscoGualdi** [oktal/pistache#335]
Hello guys.
 I'm testing the rest_description example and try to figure it out how this works and how properly set. 
Question:
1. Is it generated the .json/.yaml file following the OAS(Open Api Specification) at run time?
2. What's the correct setting form Rest::Swagger object (uiPath, uiDirectory, apiPath)?
3. The user of the API can request part of those documented request from the API?

Any information will be great.

**Comment by bkannadassan** [comment]
Did you get any input on the same ?. I am also looking for some help on the same ?. Can I write a yaml/xml and generate the code for the same ?. Any help on the same much appreciated..

rgds
Balaji

**Comment by mohsenomidi** [comment]
There is some description in issue #651, we can close this issue
