### ISSUE TITLE
Library shouldn't write to std::cout nor std::cerr.

### ISSUE THREAD

**Issue by arj** [oktal/pistache#34]
When creating a socket/endpoint, it prints
Now listening on http://127.0.0.1:9080
(or similar) std::cout.

**Comment by oktal** [comment]
Hello,

Do you think the library should not output anything at all or should it provide options to shut if off ?

**Comment by sebt3** [comment]
The library should provide the message though an "API" instead.
Call a std::function that user is free to define ;)
What would be nice would be a :
`enum levels {ok,info,notice,warning,error,critical};
std::function<void(levels,std::string)>`
for all message.
And a distinct :
`std::function<void(uint,std::string)>`
to build an acces log (http code and url).

but that's just my opinion :P

**Comment by arj** [comment]
Inside the program you already know whether the listening was successfully established or not. I think there shouldn't be a message at all. If I wanted to print one, the program using your library should do it.

Regarding the message API sebt3 suggested: I am not sure this is needed here.

**Comment by oktal** [comment]
Yes, I am also not a big fan of the `std::function` solution. I would rather provide a more elaborate logging system that you could control outside of the library to enable debug/info/trace debugging or not.

Anyway, I just removed it: https://github.com/oktal/pistache/commit/37807cea18385ca4111c81a3bcd44e846450a6dd

**Comment by arj** [comment]
Awesome, thanks!
