### ISSUE TITLE
Combinable with https://github.com/zaphoyd/websocketpp?

### ISSUE THREAD

**Issue by gabyx** [oktal/pistache#350]
Is this Library easily combinable with https://github.com/zaphoyd/websocketpp
if we want to additionaly add websockets to our code?

What makes this library better than Microsofts Rest SDK? Is it faster?

**Comment by Fylax** [comment]
The only way to know if it is faster is to benchmark it. The most notable difference is the license.

Integrating with websocket is surely possible, even though it is a very very low priority feature since having a stable release is more important right now.

**Comment by mohsenomidi** [comment]
duplicate with issue #3 
can be close.
