### ISSUE TITLE
Segmentation fault on the first try

### ISSUE THREAD

**Issue by alexe100** [oktal/pistache#437]
Hi
My first touch on Pistache...
I have compiled it using:
cd pistache
mkdir build
cd build
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install

Then;
vi hello.c
#include <pistache/endpoint.h>

using namespace Pistache;

struct HelloHandler : public Http::Handler {
    HTTP_PROTOTYPE(HelloHandler)

    void onRequest(const Http::Request& request, Http::ResponseWriter writer) {
        writer.send(Http::Code::Ok, "Hello, World!");
    }
};

int main() {
    Http::listenAndServe<HelloHandler>("*:9080");
}

Then:
g++ -g -std=gnu++11 hello.c -o hello -lpistache -lpthread

Then:
./hello
Segmentation fault (core dumped)

Then:
...
(gdb) next
153	    endpoint.init(options);
(gdb) next
154	    endpoint.setHandler(make_handler<Handler>());
(gdb) next
155	    endpoint.serve();
(gdb) step

Program received signal SIGSEGV, Segmentation fault.
0x0000000000434ec0 in Pistache::Tcp::Handler::associateTransport(Pistache::Tcp::Transport*) ()
(gdb)

What is going on?

Env: ubuntu 16

Thanks

**Comment by alexe100** [comment]
More info:
In a Web linux droplet I do:

g++ -o main main.c -lpthread -lpistache

and compiles well and executes well.

In my laptop:

g++ -o main main.c -lpthread -lpistache

shows:

In file included from /usr/include/c++/5/thread:35:0,
                 from /usr/local/include/pistache/listener.h:11,
                 from /usr/local/include/pistache/endpoint.h:9,
                 from main.c:1:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/local/include/pistache/tcp.h:12:0,
                 from /usr/local/include/pistache/listener.h:15,
                 from /usr/local/include/pistache/endpoint.h:9,
                 from main.c:1:
/usr/local/include/pistache/flags.h:19:42: error: ‘uint8_t’ was not declared in this scope
     template<> struct TypeStorage<sizeof(uint8_t)> {

(...)

Then I add it:

g++ -o main main.c -std=c++11 -lpistache -lpthread

Compiles well. Then:
$./main
Segmentation fault (core dumped)

**Comment by xurxoham** [comment]
> g++ -o main main.c -lpthread -lpistache
and compiles well and executes well.
In my laptop:
g++ -o main main.c -lpthread -lpistache
shows:

Your `main.c` file name has a wrong extension. You should be careful with that, because compilers may identify that as a C (and not a C++ file). You can use extensions such as `.C` (uppercase), `.cc`, `.c++` or `.cpp` for example.

GCC will compile different C++ standards by default depending on the compiler version. Make sure you pass `-std=c++11` or greater when you compile.

Where are you telling the library to use your specific handler? You declare it but there's no instance associated to it.

**Comment by alexe100** [comment]
After a rename:

g++ -g -std=c++11 main.cc -o main -lpistache -lpthread
$ ./main 
Segmentation fault (core dumped)

That source code is the example provided on the pistache web page. library is in /usr/libs

?

**Comment by hydratim** [comment]
The error is:
`Http::listenAndServe("*:9080");`


Which should be:
`Http::listenAndServe<HelloHandler>("*:9080");`

**Comment by alexe100** [comment]
The problem with this code:

`#include <pistache/endpoint.h>

using namespace Pistache;

struct HelloHandler : public Http::Handler {
    HTTP_PROTOTYPE(HelloHandler)

    void onRequest(const Http::Request& request, Http::ResponseWriter writer) {
        writer.send(Http::Code::Ok, "Hello, World!");
    }
};

int main() {
    Http::listenAndServe<HelloHandler>("*:9080");
}
`

Segmentation fault...

**Comment by alexe100** [comment]
`
#include <pistache/endpoint.h>

using namespace Pistache;

struct HelloHandler : public Http::Handler {
    HTTP_PROTOTYPE(HelloHandler)

    void onRequest(const Http::Request& request, Http::ResponseWriter writer) {
        writer.send(Http::Code::Ok, "Hello, World!");
    }
};

int main() {
    Http::listenAndServe<HelloHandler>("*:9080");
}
`

Sorry, this is the last version of source code and Segmentation fault too

**Comment by alexe100** [comment]
Hei, I past source code there and when I push Comment button the code inside main function is transformed. The line of code I have inside main is:
"Http::listenAndServe<HelloHandler>("*:9080");"

**Comment by alexe100** [comment]
Even using code toolbar button what is between <> desapears from the comment!

Well, hydratim I am using your code and got Segmentation fault too (on local linux box!)

**Comment by lillypad** [comment]
@hydratim and @xurxoham bring up good points.

I would recommend starting  from the beginning to be sure you have everything done correctly. Taking into account what @hydratim and @xurxoham  were saying since you are missing  the `<typename Handler>` it should not pass the compile stage at all. Also enforcing c++ 11 standards you may want to include `override` to `onRequest`. Try what I've outlined for you below, I've done this in Gentoo however it should work just fine on other distros as well.

__Initial Setup__
```bash
git clone https://github.com/oktal/pistache.git
cd pistache/
mkdir build
cd build/
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install
sudo ldconfig
cd ~
touch test.cpp
nano test.cpp
```

__test.cpp__
```cpp
#include <pistache/endpoint.h>

using namespace Pistache;

struct HelloHandler : public Http::Handler {
  HTTP_PROTOTYPE(HelloHandler)
  void onRequest(const Http::Request&, Http::ResponseWriter writer) override {
    writer.send(Http::Code::Ok, "Hello, World!");
  }
};

int main() {
  Http::listenAndServe<HelloHandler>("*:9080");
}
```

___Compile and Run the Server:___
```bash
g++ -g -std=gnu++11 test.cpp -o test -lpistache -lpthread
./test
```
__In another Terminal:___
```bash
curl http:127.0.0.1:9080
```
If this doesn't work then it could be an outdated dependency.

Hope this helps you!😄

**Comment by alexe100** [comment]
Segmentation fault (core dumped)  again...   :-(

Well, no problem for now. I am trying pistache in a droplet and it works well there. In these days I probably reinstall a fresh ubuntu in my desktop and it will work for sure. There must be problems with dependencies...

Many thanks you all!
Alex
