### ISSUE TITLE
JSON Support

### ISSUE THREAD

**Issue by Aventun** [oktal/pistache#443]
Hello
I am giving a try to Pistache (seems very attractive!  :-) ) and I have a first question but I did not find any forum or mailling list. Have you got?

If this site is not the appropriate site for this question sorry in advance:

I am trying to create a web api (rest) and I am trying the post action passing json body. 
On the service side, how can I process the json string got from req.body?
(By process I mean extract values for keys)

Should I look for an external lib to process json or pistache has that support?

I found a function called rapidJson  but i can not figure out how to use it.
Any sample code?

Thank you
Av

**Comment by xurxoham** [comment]
You are looking for something like openapi. They generate example function handlers for pistache given a YAML file with all the paths and parameters.
That code gets JSON and serialises into C++ objects.

Look for the pistache-server language generator

https://github.com/OpenAPITools/openapi-generator

**Comment by hydratim** [comment]
I'm quite the fan of using [nlohmann/json](https://github.com/nlohmann/json).

I think using it with Pistache is pretty straight forward and obvious if you use the examples from pistache and from nlohmann/json.

Let us know how it goes for you!

**Comment by Aventun** [comment]
(Ok, no native support.)
I chosen nlohmann/json too! 
Single header file, different API available, ... easy to use...
Great!
