### ISSUE TITLE
regex_replace on GCC 4.8.5

### ISSUE THREAD

**Issue by xguerin** [oktal/pistache#461]
I am hitting an issue where `regex_replace` on GCC 4.8.5 simply produce an empty string. What is the minimum compiler version required for that feature to work?

**Comment by arthurafarias** [comment]
GCC 4.9

**Comment by arthurafarias** [comment]
@xguerin, did it worked? Can we close this issue?

**Comment by xguerin** [comment]
Yes. Thanks. Closing.
