### ISSUE TITLE
How does one add header CORS in Pistache ?

### ISSUE THREAD

**Issue by GuacheSuede** [oktal/pistache#51]
Title is question, cannot seem to find any documentation on it. Thanks

**Comment by GuacheSuede** [comment]
@oktal

**Comment by Loufylouf** [comment]
Looking at the set of headers supported, it seems that Access-Control-Allow-Origin is not one of them, so you would have to add it following the documentation http://pistache.io/guide/#defining-your-own-header . I need it for a project too, so once tested, I'll probably send a PR with this header part of the official set of headers supported.

**Comment by Loufylouf** [comment]
@GuacheSuede As you can see, this is fairly simple, then you just have to add a header as you would normally with Pistache. I think it has its place in the set of headers by default as it can be very useful for jQuery users that would like to use a REST API provided by Pistache (for example).

**Comment by GuacheSuede** [comment]
Great, Thank you for the pull request.

**Comment by xinthose** [comment]
```
response.headers().add<Http::Header::AccessControlAllowOrigin>("*");
response.send(Pistache::Http::Code::Ok, "Hello World");
```

**Comment by xinthose** [comment]
> > ```
> > response.headers().add<Http::Header::AccessControlAllowOrigin>("*");
> > response.send(Pistache::Http::Code::Ok, "{\"message\":\"success\"}");
> > ```
> 
> Hi xinthose
> i add this code to my doLigin() method, but nothings happen.
> where should I add this code?

At the beginning of the route function.  So like so:

```
void doLogin (const Pistache::Rest::Request& request, Pistache::Http::ResponseWriter response)
{
    response.headers().add<Pistache::Http::Header::AccessControlAllowOrigin>("*");

    // your code
}
```

**Comment by msoodb** [comment]
> > > ```
> > > response.headers().add<Http::Header::AccessControlAllowOrigin>("*");
> > > response.send(Pistache::Http::Code::Ok, "{\"message\":\"success\"}");
> > > ```
> > 
> > 
> > Hi xinthose
> > i add this code to my doLigin() method, but nothings happen.
> > where should I add this code?
> 
> At the beginning of the route function. So like so:
> 
> ```
> void doLogin (const Pistache::Rest::Request& request, Pistache::Http::ResponseWriter response)
> {
>     response.headers().add<Pistache::Http::Header::AccessControlAllowOrigin>("*");
> 
>     // your code
> }
> ```

many thanks. this is very helpful.
