### ISSUE TITLE
Does pistache support https ?

### ISSUE THREAD

**Issue by pengweichu** [oktal/pistache#52]
Hi, does pistache support https ?

Thanks

**Comment by oktal** [comment]
Hello,

No, pistache does not yet support https

**Comment by makramkd** [comment]
Typically, you should not use a framework like pistache directly without using a proxy server like `nginx`[0]. The way I would do it is put pistache as an upstream of nginx. Nginx (or a load balancer) can terminate SSL for you, thus giving you HTTPS.

[0]: https://www.nginx.com/resources/wiki/

**Comment by pengweichu** [comment]
@makramkd In fact I need a async http client which support the https. Now I'm using the CPR, seems meet my requirements.

**Comment by oktal** [comment]
I'll try to add SSL support to the client when I get some time

**Comment by pengweichu** [comment]
@oktal I think the server side support SSL also make sense, usually we are using a C++ HTTP framework to build the REST API gateway, not depends on any other web server.

**Comment by sivapooja** [comment]
hi can i use pistache to create c++ resful service on fedora linux? and
Can i deploy it on tomcat 8 web server?

**Comment by oxoocoffee** [comment]
Would it be possible to add HTTPS support using https://github.com/randombit/botan.git ?

**Comment by nicraMarcin** [comment]
I join the question about https

**Comment by janhkrueger** [comment]
You might check the PR https://github.com/oktal/pistache/pull/226
It is worked on

**Comment by nicraMarcin** [comment]
@janhkrueger Nice, but this isn't merged yet :/

**Comment by danishmarif** [comment]
Is there a support for using https:// in the Http::Client still or just for the server?

**Comment by hydratim** [comment]
Just server as we don't actively maintain the client - However pull requests are welcome.

**Comment by timijntema** [comment]
When building the Pistache library with SSL using the -DPISTACHE_USE_SSL=true option, I noticed it is missing openssl. If this is a dependency, shouldn't it be added to the repository as a submodule and to cmake?

I know it can be installed using the command "sudo apt-get install openssl libssl-dev", but it would be nice to have it added as a submodule.

**Comment by kiplingw** [comment]
Hey timijntema. The dependency is automatically pulled when the package is built.

https://github.com/oktal/pistache/blob/master/debian/control#L14

**Comment by timijntema** [comment]
Could it be that it doesn't when you build from sources using cmake? Because thats what I did

**Comment by timijntema** [comment]
I might have found an issue as well with the Pistache https/ssl support. I used the following code:

```C++
#include <pistache/endpoint.h>
#include <iostream>

using namespace Pistache;

struct HelloHandler : public Http::Handler {
    HTTP_PROTOTYPE(HelloHandler)

    void onRequest(const Http::Request& request, Http::ResponseWriter writer) {
        writer.send(Http::Code::Ok, "Hello, World!");
    }
};

int main(void) {
    std::cout << "Starting server\n";
    Pistache::Address addr;
    auto opts = Http::Endpoint::options().threads(1);

    addr = Pistache::Address(Pistache::Ipv4::any(), Pistache::Port(9999));

    Http::Endpoint server(addr);
    server.init(opts);
    server.setHandler(std::make_shared<HelloHandler>());
    server.useSSL("./cas/server/server.crt", "./cas/server/server.key");
    server.useSSLAuth("./cas/rootCA/rootCA.crt");
    std::cout << "SSL enabled\n";

    server.serve();
    return 0;
}
```

The certificates where generated using a terminal script:

```sh
#!/bin/bash

# This script was executed from inside the cas directory seen in the C++ code above

# Generate root CA
echo "Generating rootCA"
mkdir rootCA
cd rootCA
openssl genrsa -out rootCA.key 4096
openssl req -x509 -new -nodes -key rootCA.key -subj "/C=NL/ST=UTRECHT/O=Some company/CN=rootca" -sha256 -days 1024 -out rootCA.crt
cd ..

# Generate server certificate
echo "\nGenerating server certificate"
mkdir server
cd server
openssl genrsa -out server.key 2048
openssl req -new -sha256 -key server.key -subj "/C=NL/ST=UTRECHT/O=Some company/CN=Some ip" -out server.csr
openssl x509 -req -in server.csr -CA ../rootCA/rootCA.crt -CAkey ../rootCA/rootCA.key -CAcreateserial -out server.crt -days 500 -sha256
cd ..

# Generate client certificate
echo "\nGenerating client certificate"
mkdir client
cd client
openssl genrsa -out client.key 2048
openssl req -new -sha256 -key client.key -subj "/C=NL/ST=UTRECHT/O=Some company/CN=Some ip" -out client.csr
openssl x509 -req -in client.csr -CA ../rootCA/rootCA.crt -CAkey ../rootCA/rootCA.key -CAcreateserial -out client.crt -days 500 -sha256
cd ..
```

And then I ran the command line curl request `curl https://127.0.0.1:9999 --cacert rootCA/rootCA.crt --cert client/client.crt --key client/client.key -k -v`

I performed two curl requests using the same line without restarting the server. The first provides me with status code OK and the hello world text. The second one gives me an error:

```
# CURL output

* Expire in 0 ms for 6 (transfer 0x564eefb7f5c0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x564eefb7f5c0)
* Connected to 127.0.0.1 (127.0.0.1) port 9999 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: rootCA/rootCA.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=NL; ST=UTRECHT; O=Some company; CN=Some ip
*  start date: Jun  5 06:50:35 2019 GMT
*  expire date: Oct 17 06:50:35 2020 GMT
*  issuer: C=NL; ST=UTRECHT; O=Some company; CN=rootca
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: 127.0.0.1:9999
> User-Agent: curl/7.64.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.3 (OUT), TLS alert, bad record mac (532):
* OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
* Closing connection 0
curl: (56) OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0


# Pistache output
Starting server
SSL enabled
terminate called after throwing an instance of 'std::runtime_error'
  what():  Success
Aborted (core dumped)
```

The reason I am not creating an issue is that I might have done something wrong. Could someone either confirm this is an issue or tell me what I did wrong. Another bit of information is that the second request does not error in the handler. It errors before the handler is called.

WARNING: The certificates generated by the terminal script might not be fully save. I am no expert in ssl and I chose to remove the password from the certificate generation. Make sure you check if the certificates are save before you use them.

**Comment by timijntema** [comment]
> > Could it be that it doesn't when you build from sources using cmake? Because thats what I did. I assume that the provided source is meant for when you use the package manager of a given system to download the library? (apt-get install ...)
> 
> No, the source is not what the package manager uses. The build server that produces the binary packages uses the source, in addition to some other metadata in debian/*. Unless you are planning on modifying the library or experimenting with its internals, I suggest you save yourself a great deal of time and use the precompiled binaries.

I already created created a Docker container with Pistache build from sources using cmake. So thats fine, it wasn't  too much of an issue.

Does anyone have a solution to the other issue I mentioned? The one about Pistache throwing a std::runtime error on the second curl request when using ssl.

**Comment by hydratim** [comment]
Could you open a new ticket for that please, with the sample code strace and specific curl request.

**Comment by timijntema** [comment]
> Could you open a new ticket for that please, with the sample code strace and specific curl request.

New issue #549

**Comment by hydratim** [comment]
Thanks

**Comment by mohsenomidi** [comment]
It supports HTTPS, and we could close this issue.

**Comment by Pasarel** [comment]
> Just server as we don't actively maintain the client - However pull requests are welcome.

Is this still the case at the present moment?

**Comment by kiplingw** [comment]
Indeed.
