### ISSUE TITLE
How-to cross compile on ARMv6 (Raspberry Pi Zero)

### ISSUE THREAD

**Issue by NoobTW** [oktal/pistache#534]
It may be a little bit off-topic. But how to cross-compile pistache on Raspbian on Raspberry Pi Zero?

It's almost impossible to compile it on RasPi Zero, I think it's memory issue:

> virtual memory exhausted: cannot allocate memory

BTW, I'm successfully compiled without ssl lib, unit tests, docs, and examples.

**Comment by arthurafarias** [comment]
Try enabling huge pages in the kernel. When I was working with embedded arm linux. The huge pages kernel flag disabled leaded to this kind of error.

**Comment by hydratim** [comment]
If this solution is accepted can you close the ticket please?
