### ISSUE TITLE
Handling URL in GET requests

### ISSUE THREAD

**Issue by dendisuhubdy** [oktal/pistache#537]
Does anyone know how I can pass URL's in GET request using PIstache? For example `http://host/record/url=http://other_host/image.jpg`?

I tried following the `rest_server.cc` and succeeded in passing other (than URL) values.

**Comment by arthurafarias** [comment]
I think should encode this url before sending to the server and decode the URL parameter in the server.

**Comment by dendisuhubdy** [comment]
Got it! I did this at the end

```
private:
    void setupRoutes() {
        using namespace Rest;
        Routes::Post(router, "/", Routes::bind(&StatsEndpoint::doRead, this));
    }

    void doRead(const Rest::Request& request, Http::ResponseWriter response) {
        auto url = request.body();
```

and sent the URL via the body of the POST request like `curl -d "https://img.tradera.net/images/189/89_78c60895-72c7-4d4e55.jpg" -X POST http://host/`
