### ISSUE TITLE
Custom Clone(obj*)  method

### ISSUE THREAD

**Issue by cneira** [oktal/pistache#54]
Hello,
Currently I need a clone with this signature.
 ```c++ 
std::shared_ptr<Net::Tcp::Handler> clone(Uservice_Interface* usvc) const {
        return std::make_shared<Endpoint>(usvc) ;
    } typedef Net::Http::details::prototype_tag tag;
```

 But, it does not  work as clone() is required for a http_prototype, 
Is it possible to specify a custom clone in a Http Handler ?. 
My current issue is that I need to pass parameters to the constructor of my http handler class.

**Comment by oktal** [comment]
Hello,

Have you figured out a workaround for your issue ?

**Comment by cneira** [comment]
Hi,
Yes, I just created a template that sets in my class a functor that process the http request.

Bests

**Comment by cneira** [comment]
Hi, 

I think it would be really good to have a overloaded clone() call, as I would like to initialize my object that is being cloned.
