### ISSUE TITLE
How are more requests than threads handled?

### ISSUE THREAD

**Issue by bigerl** [oktal/pistache#540]
I have a question about the way pistache handles requests by multiple clients. 
How does pistache handle more parallel request than it was assigned threads. 
- Does it queue them? 
- Does it cancel them?
- Or does it just ignore them?

Background: For 16/32 clients sending in parallel one request after another, I have a lot of failed requests against the pistache endpoint. The endpoint is assigned 16/32 threads. 
The experiments are executed on a single machine with two Xeon E5-2683 v4 ( 16 cores / 32 threads each) and 512 GB ram. So resources should not be a problem in my opinion. 
Note: the failing queries occur only if the requests are handled very fast. For workloads with a lot of requests that take some time to process the problem did not occur.

**Comment by hydratim** [comment]
Pistache relies on the kernel managed queuing from <sys/socket.h>, here's a snippet from the header:

```
/* Prepare to accept connections on socket FD.
   N connection requests will be queued before further requests are refused.
   Returns 0 on success, -1 for errors.  */
extern int listen (int __fd, int __n) __THROW;

/* Await a connection on socket FD.
   When a connection arrives, open a new socket to communicate with it,
   set *ADDR (which is *ADDR_LEN bytes long) to the address of the connecting
   peer and *ADDR_LEN to the address's actual length, and return the
   new socket's descriptor, or -1 for errors.

   This function is a cancellation point and therefore not marked with
   __THROW.  */
extern int accept (int __fd, __SOCKADDR_ARG __addr,
		   socklen_t *__restrict __addr_len);
```

By default we set this to 128, though you could set it to what you like via `Http::Endpoint::options` for example: 
```
auto opts = Http::Endpoint::options()
            .threads(thr)
            .backlog(256)
            .flags(Tcp::Options::InstallSignalHandler);
```

**Comment by mohsenomidi** [comment]
Answered issue, we can close it
