### ISSUE TITLE
Apache benchmark fails after 1 request

### ISSUE THREAD

**Issue by bosim** [oktal/pistache#56]
Hi

I just wanted to test the performance of "rest_server". However apache benchmark just sends one request and then stalls.

```
bo@alpha:~/tmp/pistache> ab -v4 -c 1 -n 100 http://127.0.0.1:9080/ready/
This is ApacheBench, Version 2.3 <$Revision: 1748469 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)...INFO: GET header == 
---
GET /ready/ HTTP/1.0
Host: 127.0.0.1:9080
User-Agent: ApacheBench/2.3
Accept: */*


---
LOG: header received:
HTTP/1.0 200 OK
Connection: Keep-Alive
Content-Length: 1

1
LOG: Response code = 200
^C

Server Software:        
Server Hostname:        127.0.0.1
Server Port:            9080

Document Path:          /ready/
Document Length:        0 bytes

Concurrency Level:      1
Time taken for tests:   0.908 seconds
Complete requests:      0
Failed requests:        0
Total transferred:      63 bytes
HTML transferred:       1 bytes

```

**Comment by oktal** [comment]
Hello,

Try using the `-k` option to make connections `Keep-Alive`.

Currently, Pistache always adds a `Keep-Alive` to response headers, which apparently makes ab hang.
I left comments in the code to address that case (i.e connections that are not `Keep-Alive`), but for now, if you want to perf test the server, just just keep alive.

**Comment by bosim** [comment]
Hi
Thanks for your response. So '``ab``` expect ```Connection: close```?
The request per second looks pretty good!
Bo

**Comment by cneira** [comment]
I'm trying to test a a rest api, but I don't get the actual response from the server

ab -n 2  -k -v 4 -c 2  -T 'Content-Type: application/json' -p test0.json   -H 'Accept: application/json'    http://127.0.0.1:9029/

I'm only get 200 ok response but not the json response that the server delivers. Using curl works fine

url -i -H 'Accept: application/json' -X POST -d @test0.json  http://localhost:9029/

Did I miss a parameter on AB ?

**Comment by oktal** [comment]
Hello, does `ab` send a `POST` request like you do in your curl request ?

If you do not support `GET` requests in your handler, you won't get a response from the server

**Comment by metamaker** [comment]
@cneira I am having same problem, but when I use https://github.com/Microsoft/cpprestsdk based application with `ab`. Have you found solution?

**Comment by cneira** [comment]
keep alive was the solution:

ab -v 4 -n 20000  -k  -c 200   http://127.0.0.1:9032/services/script1
I'm using it here
[example](https://github.com/cneira/Taraxacum/blob/master/examples/Rest/tests/test.sh)
