### ISSUE TITLE
TEST(cookie_test, attributes_test) bus error on armhf

### ISSUE THREAD

**Issue by kiplingw** [oktal/pistache#599]
The tests/cookie_test.cc's attributes_test for the cookie_test suite on armhf segfaults. This test passes on all other PPA supported architectures (amd64, i386, s390s, ppc64el, and arm64). It only happens on armhf.

I am in the process of debugging still because the issue is very difficult to reproduce in a local build tree / sbuild. It does, however, occur with every build in our PPA and only on the server's pbuilder environment.

The crash appears to occur somewhere within the following. Note that the lambda is never invoked, so it must be within the parse() call.

```
    parse("lang=en-US; Expires=Wed, 09 Jun 2021 10:18:14 GMT", [](const Cookie& c) {
```

Tracing further into the parse() call using crude logging of line numbers to stdout in pbuilder, execution manages to venture into cookie.cc:

```
    template<typename T>
    bool match_attribute(const char* name, size_t len, StreamCursor& cursor, Cookie* obj, T Cookie::*attr) {
        if (match_string(name, len, cursor)) {
/* crashes on next line */
            AttributeMatcher<T>::match(cursor, obj, attr);
            cursor.advance(1);

            return true;
        }

        return false;
    }
```

**Comment by kurahaupo** [comment]
The data members of Optional are unint8_t[] and a bool, so they don't carry any useful alignment.

Any fix to this will need to adjust the PistacheCheckSize to round up the expected size to a multiple of alignof

**Comment by kiplingw** [comment]
Thanks @kurahaupo. It took a few days of debugging, but appreciate your help today in the nuances of alignof operator on IRC.
