### ISSUE TITLE
Web Sockets - does anybody need this?

### ISSUE THREAD

**Issue by nicraMarcin** [oktal/pistache#619]
Does anyone need web sockets to his projects?
My c++ knowledge is weak yet, I'm learning it but maybe someone who need or can add this to pistache could be so kind do it?

**Comment by nicraMarcin** [comment]
Yes, I can but the websocket you provided needs another external dependieces such as boost.
Pistache is written with no external libraries and this is good and I can't find if the websocketpp supports threads.

**Comment by yvesdm3000** [comment]
Yes we would like to have websockets here...

**Comment by DarkWingMcQuack** [comment]
I would love to see websockets in pistache

**Comment by mohsenomidi** [comment]
duplicated by issue #3 
could be closed.
