### ISSUE TITLE
Broken build after merge of Ne02ptzero:work/louis/sendfile_tls 

### ISSUE THREAD

**Issue by AgentJandK** [oktal/pistache#621]
When building according to Getting Started guide, the build fails with following error:

> .../pistache/src/common/utils.cc:10:22: error: ‘SSL’ was not declared in this scope
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                      ^~~
.../pistache/src/common/utils.cc:10:27: error: ‘out’ was not declared in this scope
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                           ^~~
.../pistache/src/common/utils.cc:10:32: error: expected primary-expression before ‘int’
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                ^~~
.../pistache/src/common/utils.cc:10:46: error: expected primary-expression before ‘*’ token
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                              ^
.../pistache/src/common/utils.cc:10:47: error: ‘offset’ was not declared in this scope
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                               ^~~~~~
.../pistache/src/common/utils.cc:10:47: note: suggested alternative: ‘off_t’
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                               ^~~~~~
                                               off_t
.../pistache/src/common/utils.cc:10:62: error: expected primary-expression before ‘count’
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                                              ^~~~~
.../pistache/src/common/utils.cc:10:67: error: expression list treated as compound expression in initializer [-fpermissive]
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                                                   ^
make[2]: *** [src/CMakeFiles/pistache.dir/build.make:258: src/CMakeFiles/pistache.dir/common/utils.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:127: src/CMakeFiles/pistache.dir/all] Error 2
make: *** [Makefile:152: all] Error 

Issue seems to be in file **_src/common/utils.cc _** it is compiled unconditionally even if the build is performed without **_PISTACHE_USE_SSL_** option set.
Solution:
Either add the necessary _**#ifdef**_ to file or make the exclusion in **_CMakefile.txt_** based on the option.

**Comment by Ne02ptzero** [comment]
That's my bad. I'll make a PR right away. In the meantime, you can compile with `PISTACHE_USE_SSL` (and not use SSL, it's fine), or apply this patch in your local tree:

```
diff --git a/src/common/utils.cc b/src/common/utils.cc
index 99a3e99..8111580 100644
--- a/src/common/utils.cc
+++ b/src/common/utils.cc
@@ -7,6 +7,8 @@
 #include <pistache/peer.h>
 #include <unistd.h>
 
+#ifdef PISTACHE_USE_SSL
+
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
 {
     unsigned char       buffer[4096] = { 0 };
@@ -33,3 +35,5 @@ ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
 
     return written;
 }
+
+#endif /* PISTACHE_USE_SSL */
```

**Comment by AgentJandK** [comment]
I just set the PISTACHE_USE_SSL otion and it works fine. Thanks.
