### ISSUE TITLE
Master failed to compile!

### ISSUE THREAD

**Issue by sanjayahf** [oktal/pistache#622]
When I use Pistache as an external dependency, it fails to compile with the latest commits to the master. I get the following  error:

`[  4%] Building CXX object src/CMakeFiles/pistache.dir/common/utils.cc.o
/service/build/PISTACHE-prefix/src/PISTACHE/src/common/utils.cc:10:22: error: 'SSL' was not declared in this scope
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                      ^~~
/service/build/PISTACHE-prefix/src/PISTACHE/src/common/utils.cc:10:27: error: 'out' was not declared in this scope
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                           ^~~
/service/build/PISTACHE-prefix/src/PISTACHE/src/common/utils.cc:10:32: error: expected primary-expression before 'int'
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                ^~~
/service/build/PISTACHE-prefix/src/PISTACHE/src/common/utils.cc:10:46: error: expected primary-expression before '*' token
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                              ^
/service/build/PISTACHE-prefix/src/PISTACHE/src/common/utils.cc:10:47: error: 'offset' was not declared in this scope
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                               ^~~~~~
/service/build/PISTACHE-prefix/src/PISTACHE/src/common/utils.cc:10:47: note: suggested alternative: 'off_t'
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                               ^~~~~~
                                               off_t
/service/build/PISTACHE-prefix/src/PISTACHE/src/common/utils.cc:10:62: error: expected primary-expression before 'count'
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                                              ^~~~~
/service/build/PISTACHE-prefix/src/PISTACHE/src/common/utils.cc:10:67: error: expression list treated as compound expression in initializer [-fpermissive]
 ssize_t SSL_sendfile(SSL *out, int in, off_t *offset, size_t count)
                                                                   ^
src/CMakeFiles/pistache.dir/build.make:422: recipe for target 'src/CMakeFiles/pistache.dir/common/utils.cc.o' failed
make[5]: *** [src/CMakeFiles/pistache.dir/common/utils.cc.o] Error 1
CMakeFiles/Makefile2:121: recipe for target 'src/CMakeFiles/pistache.dir/all' failed
make[4]: *** [src/CMakeFiles/pistache.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/PISTACHE.dir/build.make:110: recipe for target 'PISTACHE-prefix/src/PISTACHE-stamp/PISTACHE-build' failed
make[2]: *** [PISTACHE-prefix/src/PISTACHE-stamp/PISTACHE-build] Error 2
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/PISTACHE.dir/all' failed
make[1]: *** [CMakeFiles/PISTACHE.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

Also can you please start adding tags for release versions, I have to use a commit hash to get a working version.

Thanks
Sanjaya

**Comment by Ne02ptzero** [comment]
That's my bad, see https://github.com/oktal/pistache/issues/621
