### ISSUE TITLE
Windows support soon?

### ISSUE THREAD

**Issue by AdavizeTheFirst** [oktal/pistache#649]
This is a very great framework I'd like to know whether to expect any support for windows soon. 
The website says "No support for windows yet".

**Comment by kiplingw** [comment]
Hey @AdavizeTheFirst. I can't speak for the other maintainers, but as for myself I don't see any reason for triaging resources on legacy systems. Windows isn't just disappearing on the desktop, but it's already virtually gone in the server world which is where Pistache always had its primary application.

**Comment by Asimov500** [comment]
I am not botherd if there is a windows version but windows isn't disappearing on the desktop anywhere I have been. I am a web developer at work and windows is certainly not disappearing. I also run a windows 2012 server. I have seen no sign of windows disappearing anywhere?? I am also a 3D modeller and it isn't something I would like to do on a linux computer that can't run 3ds Max. Windows is far from being dead.

**Comment by kiplingw** [comment]
If you are making websites then you don't have any need for Pistache. If you are developing a high performance server written in C++ with a REST API, then you have a use case. 

As for CentOS, Pistache should build on any GNU system. The pre-compiled packages are prepared for Ubuntu, but the source is portable across different GNU systems. The packages are just convenience packages to save from having to build and run DEP-8 tests.

**Comment by Asimov500** [comment]
I do web development but I also write C++ code. We have php apis which are  on our centos server. We are currently converting some of our apis to C++ for extra speed. We have got it working in Ubuntu but had a lot of trouble trying to compile it for Centos. I totally understand why you don't wish to support windows, but it is far from being dead.

**Comment by kiplingw** [comment]
@Asimov500, if this is a company you work for, tell them to reach out to me and I can help them port and package it for CentOS.

**Comment by hydratim** [comment]
There is a fundamental network stack reason we don't support windows.
Please search for tickets before raising a new one: https://github.com/oktal/pistache/issues/6
