### ISSUE TITLE
Compiling with pistache.io

### ISSUE THREAD

**Issue by RanjKuru** [oktal/pistache#67]
I did not see how to compile pistache.io examples. The compiling threw following error
`In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/string:41,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from /srv/Workspaces/nithu/FrontPage/register_service/src/RegisterServiceServlet.hh:9,
                 from /srv/Workspaces/nithu/FrontPage/register_service/src/RegisterServiceServlet.cc:8:
/usr/include/c++/5/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = RegisterServiceServlet; _Args = {}; _Tp = RegisterServiceServlet]’:
/usr/include/c++/5/bits/alloc_traits.h:530:4:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = RegisterServiceServlet; _Args = {}; _Tp = RegisterServiceServlet; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<RegisterServiceServlet>]’
/usr/include/c++/5/bits/shared_ptr_base.h:522:39:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {}; _Tp = RegisterServiceServlet; _Alloc = std::allocator<RegisterServiceServlet>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/usr/include/c++/5/bits/shared_ptr_base.h:617:4:   required from ‘std::__shared_count<_Lp>::__shared_count(std::_Sp_make_shared_tag, _Tp*, const _Alloc&, _Args&& ...) [with _Tp = RegisterServiceServlet; _Alloc = std::allocator<RegisterServiceServlet>; _Args = {}; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/usr/include/c++/5/bits/shared_ptr_base.h:1097:35:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<RegisterServiceServlet>; _Args = {}; _Tp = RegisterServiceServlet; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/usr/include/c++/5/bits/shared_ptr.h:319:64:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<RegisterServiceServlet>; _Args = {}; _Tp = RegisterServiceServlet]’
/usr/include/c++/5/bits/shared_ptr.h:620:39:   required from ‘std::shared_ptr<_Tp1> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = RegisterServiceServlet; _Alloc = std::allocator<RegisterServiceServlet>; _Args = {}]’
/usr/include/c++/5/bits/shared_ptr.h:635:39:   required from ‘std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = RegisterServiceServlet; _Args = {}]’
/srv/Workspaces/nithu/FrontPage/register_service/src/RegisterServiceServlet.hh:23:3:   required from here
/usr/include/c++/5/ext/new_allocator.h:120:4: error: invalid new-expression of abstract class type ‘RegisterServiceServlet’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
compilation terminated due to -Wfatal-errors.
CMakeFiles/consoleTest_Register_Service.dir/build.make:65: recipe for target 'CMakeFiles/consoleTest_Register_Service.dir/src/RegisterServiceServlet.cc.o' failed
make[2]: *** [CMakeFiles/consoleTest_Register_Service.dir/src/RegisterServiceServlet.cc.o] Error 1
make[2]: Leaving directory '/srv/Workspaces/nithu/FrontPage/register_service/build'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/consoleTest_Register_Service.dir/all' failed
make[1]: *** [CMakeFiles/consoleTest_Register_Service.dir/all] Error 2
make[1]: Leaving directory '/srv/Workspaces/nithu/FrontPage/register_service/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
$`

**Comment by oktal** [comment]
Hello,

The error does not really come from pistache itself:

`error: invalid new-expression of abstract class type ‘RegisterServiceServlet’`

Looks like your `RegisterServiceServlet` class is abstract (one of the member function is virtual pure).

**Comment by RanjKuru** [comment]
I am afraid you are right and I apoligize for that thread. My mistake.

**Comment by oktal** [comment]
Closing this issue
