### ISSUE TITLE
example compilation issue Ubuntu 16.04

### ISSUE THREAD

**Issue by xens** [oktal/pistache#71]
Hi,

I'm having troubles to compile the hello world example below:

```
#include <pistache/endpoint.h>

using namespace Net;

struct HelloHandler : public Http::Handler {
    void onRequest(const Http::Request& request, Http::ResponseWriter writer) {
                writer.send(Http::Code::Ok, "Hello, World!");

    }

};

int main() {
        Http::listenAndServe<HelloHandler>("*:9080");

}
```
compilation: `gcc -std=c++11 hello.cc`

```
In file included from /usr/local/include/pistache/endpoint.h:11:0,
                 from hello.cc:1:
/usr/local/include/pistache/http.h: In instantiation of ‘std::shared_ptr<_Tp1> Net::Http::make_handler(Args&& ...) [with H = HelloHandler; Args = {}]’:
/usr/local/include/pistache/endpoint.h:93:46:   required from ‘void Net::Http::listenAndServe(Net::Address, const Net::Http::Endpoint::Options&) [with Handler = HelloHandler]’
/usr/local/include/pistache/endpoint.h:85:28:   required from ‘void Net::Http::listenAndServe(Net::Address) [with Handler = HelloHandler]’
hello.cc:14:52:   required from here
/usr/local/include/pistache/http.h:758:5: error: static assertion failed: An http handler must be an http prototype, did you forget the HTTP_PROTOTYPE macro ?
     static_assert(details::IsHttpPrototype<H>::value, "An http handler must be an http prototype, did you forget the HTTP_PROTOTYPE macro ?");
```
gcc: 4:5.3.1-1ubuntu1

thanks for your help !

**Comment by oktal** [comment]
Hello,

If you look carefully at the compile error, you'll see that you triggered a static assertion:

`/usr/local/include/pistache/http.h:758:5: error: static assertion failed: An http handler must be an http prototype, did you forget the HTTP_PROTOTYPE macro ?`

You have to use the `HTTP_PROTOTYPE` macro in your Handler:

```cpp
struct HelloHandler : public Http::Handler {

    HTTP_PROTOTYPE(HelloHandler)

    void onRequest(const Http::Request& request, Http::ResponseWriter writer) {
                writer.send(Http::Code::Ok, "Hello, World!");

    }

};
```

I'll update the README

**Comment by xens** [comment]
Thanks, I'm going further but here's the next issue:
```
gcc -std=c++11 hello.cc
/tmp/ccVAa4xI.o: In function `main':
hello.cc:(.text+0x13d): undefined reference to `Net::Address::Address(char const*)'
/tmp/ccVAa4xI.o: In function `__static_initialization_and_destruction_0(int, int)':
hello.cc:(.text+0x1b8): undefined reference to `std::ios_base::Init::Init()'
hello.cc:(.text+0x1c7): undefined reference to `std::ios_base::Init::~Init()'
/tmp/ccVAa4xI.o: In function `Async::PromiseBase::~PromiseBase()':
hello.cc:(.text._ZN5Async11PromiseBaseD2Ev[_ZN5Async11PromiseBaseD5Ev]+0x29): undefined reference to `operator delete(void*)'
/tmp/ccVAa4xI.o: In function `Async::PromiseBase::~PromiseBase()':
hello.cc:(.text._ZN5Async11PromiseBaseD0Ev[_ZN5Async11PromiseBaseD5Ev]+0x20): undefined reference to `operator delete(void*)'
/tmp/ccVAa4xI.o: In function `Net::Http::Mime::MediaType::MediaType()':
hello.cc:(.text._ZN3Net4Http4Mime9MediaTypeC2Ev[_ZN3Net4Http4Mime9MediaTypeC5Ev]+0x38): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
/tmp/ccVAa4xI.o: In function `Net::Http::Header::Header::~Header()':
hello.cc:(.text._ZN3Net4Http6Header6HeaderD2Ev[_ZN3Net4Http6Header6HeaderD5Ev]+0xd): undefined reference to `vtable for Net::Http::Header::Header'
hello.cc:(.text._ZN3Net4Http6Header6HeaderD2Ev[_ZN3Net4Http6Header6HeaderD5Ev]+0x29): undefined reference to `operator delete(void*)'
/tmp/ccVAa4xI.o: In function `Net::Http::Header::Header::~Header()':
hello.cc:(.text._ZN3Net4Http6Header6HeaderD0Ev[_ZN3Net4Http6Header6HeaderD5Ev]+0x20): undefined reference to `operator delete(void*)'
/tmp/ccVAa4xI.o: In function `Net::Http::Header::Header::Header()':

```

**Comment by oktal** [comment]
You should:

1/ Compile with `g++`, not `gcc`.
2/ Make sure to link with `-lnet`

**Comment by xens** [comment]
I'm certainly missing something, still got errors with g++

g++ -lnet -std=c++11 hello.cc
/tmp/ccxhJsLk.o: In function `main':
hello.cc:(.text+0x13d): undefined reference to `Net::Address::Address(char const*)'
/tmp/ccxhJsLk.o: In function `Net::Http::Header::Header::~Header()':
hello.cc:(.text._ZN3Net4Http6Header6HeaderD2Ev[_ZN3Net4Http6Header6HeaderD5Ev]+0xd): undefined reference to `vtable for Net::Http::Header::Header'
/tmp/ccxhJsLk.o: In function `Net::Http::Header::Header::Header()':
hello.cc:(.text._ZN3Net4Http6Header6HeaderC2Ev[_ZN3Net4Http6Header6HeaderC5Ev]+0x9): undefined reference to `vtable for Net::Http::Header::Header'
/tmp/ccxhJsLk.o: In function `Net::Http::Header::ContentType::ContentType(Net::Http::Mime::MediaType const&)':
hello.cc:(.text._ZN3Net4Http6Header11ContentTypeC2ERKNS0_4Mime9MediaTypeE[_ZN3Net4Http6Header11ContentTypeC5ERKNS0_4Mime9MediaTypeE]+0x1e): undefined reference to `vtable for Net::Http::Header::ContentType'

**Comment by oktal** [comment]
How did you build and install Pistache ?

**Comment by xens** [comment]
I followed this guide: http://pistache.io/quickstart#installing-pistache

**Comment by jlesech** [comment]
I've had the same issue. I had to execute the ldconfig command as root.

**Comment by jeffvandyke** [comment]
Similar errors for me, even after ldconfig. However, the guide to compile the sources also compiles the examples, and there's a working binary of http_server under pistache/build/examples. Some more investigation needed...

**Comment by xens** [comment]
same issues as @jeffvandyke running `ldconfig` doesn't help

**Comment by dynahcatq** [comment]
same issue here. ldconfig helps but after executing my binary it throws:

terminate called after throwing an instance of 'std::invalid_argument'
  what():  Invalid address
Aborted (core dumped)

any luck?

**Comment by jeffvandyke** [comment]
Solved... Would anyone else have guessed that `-lnet` had to come after the name of the source file? I tested a bit and that seems to be the case.

Final command: `g++ demo.cpp -lnet -std=c++11 -o demo`

**Comment by xens** [comment]
@jeffvandyke t-h-a-n-k-y-o-u ! Working as expected with `-lnet` after the source
