### ISSUE TITLE
Trying to run Hello World Example on Raspberry Pi

### ISSUE THREAD

**Issue by wrmichaelmak** [oktal/pistache#789]
Background:
I compiled and installed pistache on a Raspberry Pi 3B running Raspbian 10 Buster. Although there were a couple of warnings about something like int conversion, there were no visible errors which caused the compilation or installation to fail. I followed the installation process given in the `README.md` except i removed the last line so that my pistache installation is made to `/usr/local` instead. 

Problem: 
However, when I tried to execute the Hello World Example on the Raspberry Pi given in `README.md`. I got the error `error while loading shared libraries: libpistache.so.0: cannot open shared object file: No such file or directory`. Note that I was able to build and compile the Hello World Example successfully using the Geany editor (for simplicity sake) using the following build and compile commands:

Compile:
`g++ -Wall -c "%f" -lpistache -lpthread`

Build:
`g++ -Wall -o "%e" "%f" -lpistache -lpthread`

**Comment by kiplingw** [comment]
@wrmichaelmak, what does pkg-config report?

`$ pkg-config --cflags --libs libpistache`

**Comment by wrmichaelmak** [comment]
@kiplingw thank you for your reply.

Here's what I got:
`-I/usr/local/include// -L/usr/local/lib// -lpistache -lpthread -latomic -lssl -lcrypto`

Actually I have fixed the problem. When you compile and build you will need to add where pistache is installed as one of the compiler's options. The thing that puzzled me was I only need to include it once and build & compile, then subsequent build & compiles do not need the location of where pistache is installed at.

The commands I used for the successful build and compile are:

Compile:
`g++ -Wall -c "%f" -I/usr/local/include/ -L/usr/local/lib/ -lpistache -pthread`

Build:
`g++ -Wall -o "%e" "%f" -I/usr/local/include/ -L/usr/local/lib/ -lpistache -lpthread`

**Comment by kiplingw** [comment]
Yeah as a general rule don't ever manually specify the compile and linker flags explicitly on the command line for a library, unless you are trying to override them. Use those supplied by the pkg-config manifest since that's why the package supplies them. Substitute `pkg-config --cflags --libs libpistache` as a shell substitution for what you've explicitly provided.

**Comment by wrmichaelmak** [comment]
Sorry how do I do that? I am still pretty new to this.

**Comment by kiplingw** [comment]
[This](https://people.freedesktop.org/~dbn/pkg-config-guide.html#faq) should hopefully help. The reason you should always use pkg-config over explicitly writing the compiler and linker settings is that the package maintainer may end up changing the recommended flags. If you don't know they changed your build environment could break. This way the migration can happen automatically.

**Comment by wrmichaelmak** [comment]
Alright I see. Ok i will close the issue now. Thank you very much!

**Comment by kiplingw** [comment]
No problem. Good luck and happy hacking.
