### ISSUE TITLE
Link error: multiple undefined references

### ISSUE THREAD

**Issue by archaro** [oktal/pistache#817]
I'm looking at Pistache as a possible replacement for mongoose in a project.  To this end, I've installed the PPA unstable package on my Ubuntu 20.04 installation (gcc version 9.3.0).  I've tried vanilla c++, and also passing -std=c++14 and -std=c++17, with no success.

Unfortunately, I'm unable to compile the 'hello world' example, which gives the trace below.  I've had similar problems compiling any of the examples by hand, although they compile fine with cmake (which I have no experience of).  I'd be very grateful if someone would tell me what I'm doing wrong. :)

Also (special bonus question): does Pistache play nicely with libev?

g++ `pkg-config --cflags --libs libpistache` -o hello hello.cpp
/usr/bin/ld: /tmp/ccPddlMg.o: in function `main':
hello.cpp:(.text+0x27): undefined reference to `Pistache::Http::Endpoint::options()'
/usr/bin/ld: hello.cpp:(.text+0x3d): undefined reference to `Pistache::Address::Address(char const*)'
/usr/bin/ld: /tmp/ccPddlMg.o: in function `Pistache::Http::Handler::~Handler()':
hello.cpp:(.text._ZN8Pistache4Http7HandlerD2Ev[_ZN8Pistache4Http7HandlerD5Ev]+0x13): undefined reference to `vtable for Pistache::Http::Handler'
/usr/bin/ld: hello.cpp:(.text._ZN8Pistache4Http7HandlerD2Ev[_ZN8Pistache4Http7HandlerD5Ev]+0x26): undefined reference to `Pistache::Tcp::Handler::~Handler()'
/usr/bin/ld: /tmp/ccPddlMg.o: in function `Pistache::Async::Promise<long> Pistache::Http::ResponseWriter::send<14ul>(Pistache::Http::Code, char const (&) [14ul], Pistache::Http::Mime::MediaType const&)':
hello.cpp:(.text._ZN8Pistache4Http14ResponseWriter4sendILm14EEENS_5Async7PromiseIlEENS0_4CodeERAT__KcRKNS0_4Mime9MediaTypeE[_ZN8Pistache4Http14ResponseWriter4sendILm14EEENS_5Async7PromiseIlEENS0_4CodeERAT__KcRKNS0_4Mime9MediaTypeE]+0x4e): undefined reference to `Pistache::Http::ResponseWriter::sendImpl(Pistache::Http::Code, char const*, unsigned long, Pistache::Http::Mime::MediaType const&)'
/usr/bin/ld: /tmp/ccPddlMg.o: in function `Pistache::Http::Endpoint::~Endpoint()':
hello.cpp:(.text._ZN8Pistache4Http8EndpointD2Ev[_ZN8Pistache4Http8EndpointD5Ev]+0x2e): undefined reference to `Pistache::Tcp::Listener::~Listener()'
/usr/bin/ld: /tmp/ccPddlMg.o: in function `void Pistache::Http::listenAndServe<HelloHandler>(Pistache::Address, Pistache::Http::Endpoint::Options const&)':
hello.cpp:(.text._ZN8Pistache4Http14listenAndServeI12HelloHandlerEEvNS_7AddressERKNS0_8Endpoint7OptionsE[_ZN8Pistache4Http14listenAndServeI12HelloHandlerEEvNS_7AddressERKNS0_8Endpoint7OptionsE]+0x35): undefined reference to `Pistache::Http::Endpoint::Endpoint(Pistache::Address const&)'
/usr/bin/ld: hello.cpp:(.text._ZN8Pistache4Http14listenAndServeI12HelloHandlerEEvNS_7AddressERKNS0_8Endpoint7OptionsE[_ZN8Pistache4Http14listenAndServeI12HelloHandlerEEvNS_7AddressERKNS0_8Endpoint7OptionsE]+0x4e): undefined reference to `Pistache::Http::Endpoint::init(Pistache::Http::Endpoint::Options const&)'
/usr/bin/ld: hello.cpp:(.text._ZN8Pistache4Http14listenAndServeI12HelloHandlerEEvNS_7AddressERKNS0_8Endpoint7OptionsE[_ZN8Pistache4Http14listenAndServeI12HelloHandlerEEvNS_7AddressERKNS0_8Endpoint7OptionsE]+0x8f): undefined reference to `Pistache::Http::Endpoint::setHandler(std::shared_ptr<Pistache::Http::Handler> const&)'
/usr/bin/ld: hello.cpp:(.text._ZN8Pistache4Http14listenAndServeI12HelloHandlerEEvNS_7AddressERKNS0_8Endpoint7OptionsE[_ZN8Pistache4Http14listenAndServeI12HelloHandlerEEvNS_7AddressERKNS0_8Endpoint7OptionsE]+0xbc): undefined reference to `Pistache::Http::Endpoint::serve()'
/usr/bin/ld: /tmp/ccPddlMg.o: in function `Pistache::Tcp::Handler::Handler(Pistache::Tcp::Handler const&)':
hello.cpp:(.text._ZN8Pistache3Tcp7HandlerC2ERKS1_[_ZN8Pistache3Tcp7HandlerC5ERKS1_]+0x2a): undefined reference to `vtable for Pistache::Tcp::Handler'
/usr/bin/ld: /tmp/ccPddlMg.o: in function `Pistache::Http::Handler::Handler(Pistache::Http::Handler const&)':
hello.cpp:(.text._ZN8Pistache4Http7HandlerC2ERKS1_[_ZN8Pistache4Http7HandlerC5ERKS1_]+0x2a): undefined reference to `vtable for Pistache::Http::Handler'
/usr/bin/ld: /tmp/ccPddlMg.o: in function `Pistache::Http::Handler::Handler()':
hello.cpp:(.text._ZN8Pistache4Http7HandlerC2Ev[_ZN8Pistache4Http7HandlerC5Ev]+0x18): undefined reference to `Pistache::Tcp::Handler::Handler()'
/usr/bin/ld: hello.cpp:(.text._ZN8Pistache4Http7HandlerC2Ev[_ZN8Pistache4Http7HandlerC5Ev]+0x1f): undefined reference to `vtable for Pistache::Http::Handler'
/usr/bin/ld: /tmp/ccPddlMg.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x28): undefined reference to `Pistache::Http::Handler::onInput(char const*, unsigned long, std::shared_ptr<Pistache::Tcp::Peer> const&)'
/usr/bin/ld: /tmp/ccPddlMg.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x30): undefined reference to `Pistache::Http::Handler::onConnection(std::shared_ptr<Pistache::Tcp::Peer> const&)'
/usr/bin/ld: /tmp/ccPddlMg.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x38): undefined reference to `Pistache::Http::Handler::onDisconnection(std::shared_ptr<Pistache::Tcp::Peer> const&)'
/usr/bin/ld: /tmp/ccPddlMg.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x48): undefined reference to `Pistache::Http::Handler::onTimeout(Pistache::Http::Request const&, Pistache::Http::ResponseWriter)'
/usr/bin/ld: /tmp/ccPddlMg.o:(.data.rel.ro._ZTI12HelloHandler[_ZTI12HelloHandler]+0x10): undefined reference to `typeinfo for Pistache::Http::Handler'
collect2: error: ld returned 1 exit status

**Comment by rconnorjohnstone** [comment]
If your compiler command is exactly as written above you need to wrap the `pkg-config --cflags --libs libpistache` part in `$()`

**Comment by archaro** [comment]
That was a bit of format-mangling.  The actual command was 

```
g++ `$(pkg-config --cflags --libs libpistache' -o hello hello.cpp
```

However, I have also tried with `$( )' and get the same error.  Out of an abundance of caution, I ran pkg-config separately and manually constructed the command:
`g++ -I/usr/include/ -L/usr/lib/x86_64-linux-gnu/ -lpistache -lpthread -lssl -lcrypto hello.cpp -o hello'

No difference.

**Comment by archaro** [comment]
Ok, I am a muppet.  I forgot that order matters when passing parameters to gcc.  Sigh.  I either have had too much coffee, or not enough. Either way, I haven't had exactly the right amount. 

_Libraries go at the end._
