### ISSUE TITLE
Make fails 

### ISSUE THREAD

**Issue by yummybian** [oktal/pistache#97]
`/root/workbench/cpp/pistache/src/common/os.cc:17:25: fatal error: pistache/io.h: No such file or directory`

I look through all source code , can't find io.h.

Anyone know how to solve it?

**Comment by williamkibira** [comment]
Hello, i had the exact same issue with the latest clone of the project , i simply went to that line mentioned and commented it out . The project compiled after that .

**Comment by oktal** [comment]
Hello,

My bad, it should be fixed now

**Comment by williamkibira** [comment]
Thanks a whole lot

**Comment by xoac** [comment]
I think it can be closed now. (?)
